c_compiler_version:    # [ppc64le]
- '7'                  # [ppc64le]
cxx_compiler_version:  # [ppc64le]
- '7'                  # [ppc64le]

c_compiler_version:    # [osx and x86_64]
- '12'                 # [osx and x86_64]
cxx_compiler_version:  # [osx and x86_64]
- '12'                 # [osx and x86_64]
